#!/usr/bin/env bash

# Only tested on NixOS, but it may work on other OS's.
# Shouldn't enabling dropbox in configuration.nix start dropbox automatically?

# 'command -v xyz' describes xyz but does not run it, allowing us to see
# whether the command exists (dropbox is installed).
# Piping to /dev/null means we don't have to see the description.
if command -v dropbox > /dev/null; then
  # TODO: is dropbox started on system startup?
  # Note that we don't want to start multiple instances.
  # Take a look at this: https://nixos.wiki/wiki/Dropbox
  # and this: https://www.dropbox.com/install
  #
  # NOTE - Before installing dropbox with this command:
  #     nix-env -iA nixos.dropbox
  # it might be necessary to be logged into the dropbox website.
 
  # If dropbox isn't running, start it
  if [[ $(pgrep -c dropbox) -eq 0 ]] ; then
    nohup dropbox &
  fi
fi
